# Generated by Django 2.2.1 on 2019-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190524_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='urlkey',
            field=models.CharField(default='1558761740', max_length=255),
        ),
    ]
