# Generated by Django 2.2.1 on 2019-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_urlkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='urlkey',
            field=models.CharField(default='1558876936', max_length=255),
        ),
    ]
